data:
  sequence_length: 365
  prediction_horizon: 1
  batch_size: 32
  num_workers: 4
  train_ratio: 0.7
  val_ratio: 0.15
  normalize: true

  dynamic_features:
    - total_precipitation
    - temperature
    - specific_humidity
    - shortwave_radiation
    - potential_energy

  static_features:
    # Terrain
    - "elev_mean"
    - "slope_mean"
    - "area_gages2"
    # Land Cover
    - "frac_forest"
    - "lai_max"
    - "lai_diff"
    - "dom_land_cover_frac"
    - "root_depth_50"
    # Soil
    - "soil_depth_statgso"
    - "soil_porosity"
    - "soil_conductivity"
    - "max_water_content"
    # Geology
    - "geol_porosity"
    - "geol_permeability"
    # One-hot encoded columns for dom_land_cover
    - "dom_land_cover_____Barren_or_Sparsely_Vegetated"
    - "dom_land_cover_____Closed_Shrublands"
    - "dom_land_cover_____Croplands"
    - "dom_land_cover_____Deciduous_Broadleaf_Forest"
    - "dom_land_cover_____Evergreen_Broadleaf_Forest"
    - "dom_land_cover_____Evergreen_Needleleaf_Forest"
    - "dom_land_cover_____Grasslands"
    - "dom_land_cover_____Mixed_Forests"
    - "dom_land_cover_____Open_Shrublands"
    - "dom_land_cover_____Savannas"
    - "dom_land_cover_____Woody_Savannas"
    - "dom_land_cover_____croplandnatural_vegetation_mosaic"
    # One-hot encoded columns for geol_class_1st
    - "geol_class_1st_Acid_plutonic_rocks"
    - "geol_class_1st_Acid_volcanic_rocks"
    - "geol_class_1st_Basic_plutonic_rocks"
    - "geol_class_1st_Basic_volcanic_rocks"
    - "geol_class_1st_Carbonate_sedimentary_rocks"
    - "geol_class_1st_Intermediate_plutonic_rocks"
    - "geol_class_1st_Intermediate_volcanic_rocks"
    - "geol_class_1st_Metamorphics"
    - "geol_class_1st_Mixed_sedimentary_rocks"
    - "geol_class_1st_Pyroclastics"
    - "geol_class_1st_Siliciclastic_sedimentary_rocks"
    - "geol_class_1st_Unconsolidated_sediments"
    # One-hot encoded columns for geol_class_2nd
    - "geol_class_2nd_Acid_plutonic_rocks"
    - "geol_class_2nd_Acid_volcanic_rocks"
    - "geol_class_2nd_Basic_plutonic_rocks"
    - "geol_class_2nd_Basic_volcanic_rocks"
    - "geol_class_2nd_Carbonate_sedimentary_rocks"
    - "geol_class_2nd_Intermediate_plutonic_rocks"
    - "geol_class_2nd_Intermediate_volcanic_rocks"
    - "geol_class_2nd_Metamorphics"
    - "geol_class_2nd_Mixed_sedimentary_rocks"
    - "geol_class_2nd_Pyroclastics"
    - "geol_class_2nd_Siliciclastic_sedimentary_rocks"
    - "geol_class_2nd_Unconsolidated_sediments"
    - "geol_class_2nd_Water_bodies"
    - "geol_class_2nd_missing"

  target_features:
    - streamflow
    - evapotranspiration