#!/usr/bin/env python3
"""
Run Chapter 4 Experiment A: Q-to-SSM transfer configurations.

This runner is dedicated to Experiment A and intentionally excludes the PUB
protocol. It executes baseline, Q-pretraining, and Q-pretrained fine-tuning
configurations generated by ``create_ch4a_q_to_ssm_configs.py``.

For fine-tuning runs, the dependency checkpoint is resolved from the matching
Q-pretraining experiment and passed explicitly to ``main.py`` through
``--init_checkpoint``.
"""

from __future__ import annotations

import argparse
import json
import sys

import torch
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from ch4_common import load_yaml, run_command, write_json


ConfigDict = Dict[str, Any]

CHECKPOINT_PRIORITY: Tuple[str, ...] = (
    "final_model.pth",
    "best_model.pth",
    "last_model.pth",
)


def load_manifest(
    manifest_path: Path,
) -> Tuple[ConfigDict, List[Path]]:
    """Load and validate an Experiment A manifest."""
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")

    with manifest_path.open("r", encoding="utf-8") as file:
        manifest = json.load(file)

    protocol = manifest.get("protocol")
    if protocol not in {None, "q_to_ssm"}:
        raise ValueError(
            "This runner accepts only the q_to_ssm protocol, "
            f"but the manifest declares protocol={protocol!r}."
        )

    configs = manifest.get("configs")
    if not isinstance(configs, list) or not configs:
        raise ValueError(
            f"Manifest contains no configuration paths: {manifest_path}"
        )

    return manifest, [Path(path) for path in configs]


def resolve_project_path(path: Path, project_root: Path) -> Path:
    """Resolve a path relative to the project root."""
    if path.is_absolute():
        return path.resolve()
    return (project_root / path).resolve()


def classify_config(config_path: Path) -> str:
    """Classify one configuration by its Experiment A stage."""
    name = config_path.stem.lower()

    if "qpre_finetune" in name:
        return "finetune"
    if "_qpre_seed" in name:
        return "pretrain"
    return "baseline"


def order_configs(configs: Iterable[Path]) -> List[Path]:
    """Order baselines, Q-pretraining, and fine-tuning configurations."""
    stage_order = {
        "baseline": 0,
        "pretrain": 1,
        "finetune": 2,
    }

    return sorted(
        configs,
        key=lambda path: (
            stage_order[classify_config(path)],
            path.stem,
        ),
    )


def select_configs(
    configs: Iterable[Path],
    subset: str,
) -> List[Path]:
    """Select a requested subset of Experiment A configurations."""
    selected: List[Path] = []

    for path in configs:
        stage = classify_config(path)

        if subset == "all":
            selected.append(path)
        elif subset == "baselines" and stage == "baseline":
            selected.append(path)
        elif subset == "pretrain" and stage == "pretrain":
            selected.append(path)
        elif subset == "finetune" and stage == "finetune":
            selected.append(path)
        elif subset == "evaluation" and stage in {
            "baseline",
            "finetune",
        }:
            selected.append(path)

    if not selected:
        raise ValueError(
            f"No configurations matched subset={subset!r}."
        )

    return selected


def extract_checkpoint_dependency(
    config: ConfigDict,
) -> Optional[str]:
    """Extract a ``__CHECKPOINT__:experiment_name`` dependency marker."""
    candidate_values: List[Any] = []

    metadata = config.get("ch4_qssm", {})
    if isinstance(metadata, dict):
        candidate_values.append(metadata.get("init_checkpoint"))

    candidate_values.append(config.get("init_checkpoint"))

    training_config = config.get("training", {})
    if isinstance(training_config, dict):
        candidate_values.append(
            training_config.get("init_checkpoint")
        )

    model_config = config.get("model", {})
    if isinstance(model_config, dict):
        candidate_values.extend(
            [
                model_config.get("init_checkpoint"),
                model_config.get("checkpoint_path"),
            ]
        )

    model_params = config.get("model_params", {})
    if isinstance(model_params, dict):
        candidate_values.append(model_params.get("weight_path"))

    for value in candidate_values:
        text = str(value or "").strip()

        if text.startswith("__CHECKPOINT__:"):
            dependency = text.split(":", 1)[1].strip()

            if not dependency:
                raise ValueError(
                    "Found an empty checkpoint dependency marker."
                )

            return dependency

    return None


def resolve_dependency_checkpoint(
    dependency_name: str,
    experiments_root: Path,
) -> Path:
    """Resolve the preferred checkpoint from a Q-pretraining experiment."""
    dependency_dir = experiments_root / dependency_name

    for checkpoint_name in CHECKPOINT_PRIORITY:
        candidate = dependency_dir / checkpoint_name
        if candidate.exists():
            return candidate.resolve()

    recursive_candidates: List[Path] = []

    for checkpoint_name in CHECKPOINT_PRIORITY:
        recursive_candidates.extend(
            path
            for path in experiments_root.rglob(checkpoint_name)
            if dependency_name in str(path.parent)
        )

    if recursive_candidates:
        priority = {
            name: index
            for index, name in enumerate(CHECKPOINT_PRIORITY)
        }

        recursive_candidates.sort(
            key=lambda path: (
                priority.get(path.name, 999),
                -path.stat().st_mtime,
            )
        )

        return recursive_candidates[0].resolve()

    raise FileNotFoundError(
        "Could not resolve a Q-pretraining checkpoint for "
        f"dependency={dependency_name!r}. Expected one of "
        f"{CHECKPOINT_PRIORITY} below {dependency_dir}."
    )



def extract_target_weights(
    config_path: Path,
    data_config: ConfigDict,
) -> Dict[str, float]:
    """Return a validated target-to-loss-weight mapping."""
    targets = data_config.get("targets", [])

    if not isinstance(targets, list) or not targets:
        raise ValueError(
            f"Missing data.targets in {config_path}."
        )

    weights: Dict[str, float] = {}

    for target in targets:
        if not isinstance(target, dict):
            raise ValueError(
                "Experiment A targets must be full dictionaries, "
                f"got {target!r} in {config_path}."
            )

        name = str(target.get("name", "")).strip().lower()

        if not name:
            raise ValueError(
                f"Target without a name in {config_path}."
            )

        if name in weights:
            raise ValueError(
                f"Duplicate target {name!r} in {config_path}."
            )

        weights[name] = float(
            target.get("loss_weight", 1.0)
        )

    return weights


def normalized_sample_filter(
    data_config: ConfigDict,
) -> Optional[ConfigDict]:
    """Normalize an optional training sample filter for auditing."""
    sample_filter = data_config.get("sample_filter")

    if sample_filter is None:
        return None

    if not isinstance(sample_filter, dict):
        raise ValueError(
            "data.sample_filter must be a dictionary or null."
        )

    return {
        "enabled": bool(sample_filter.get("enabled", False)),
        "required_valid_targets": [
            str(value).strip().lower()
            for value in sample_filter.get(
                "required_valid_targets",
                [],
            )
        ],
        "apply_to_modes": [
            str(value).strip().lower()
            for value in sample_filter.get(
                "apply_to_modes",
                [],
            )
        ],
    }


def expected_training_filter(
    task_name: str,
) -> ConfigDict:
    """Build the canonical train-only target filter."""
    return {
        "enabled": True,
        "required_valid_targets": [task_name],
        "apply_to_modes": ["train"],
    }


def audit_experiment_a_config(
    config_path: Path,
    config: ConfigDict,
    manifest: ConfigDict,
) -> None:
    """Fail fast when a manifest contains a non-Experiment-A config."""
    normalized_path = str(config_path).replace("\\", "/").lower()

    if "/pub/" in normalized_path or config_path.stem.lower().startswith("ch4b_"):
        raise ValueError(
            "PUB configuration detected in the Experiment A runner: "
            f"{config_path}"
        )

    model_config = config.get("model", {})
    if not isinstance(model_config, dict):
        raise ValueError(f"Missing model block: {config_path}")

    architecture = str(
        model_config.get("architecture", "")
    ).strip().lower()

    if architecture not in {"stl", "hps", "cgc"}:
        raise ValueError(
            f"Unsupported Experiment A architecture={architecture!r} "
            f"in {config_path}. Expected stl, hps, or cgc."
        )

    data_config = config.get("data", {})
    if not isinstance(data_config, dict):
        raise ValueError(f"Missing data block: {config_path}")

    for key in (
        "val_period",
        "valid_period",
        "validation_period",
    ):
        if data_config.get(key) is not None:
            raise ValueError(
                f"Experiment A requires {key}=None in {config_path}."
            )

    target_weights = extract_target_weights(
        config_path,
        data_config,
    )
    sample_filter = normalized_sample_filter(data_config)

    training_config = config.get("training", {})
    if not isinstance(training_config, dict):
        raise ValueError(
            f"Missing training block: {config_path}"
        )

    early_stopping = training_config.get(
        "early_stopping",
        {},
    )
    if (
        isinstance(early_stopping, dict)
        and bool(early_stopping.get("enabled", False))
    ):
        raise ValueError(
            "Experiment A fixed-epoch runs must disable "
            f"early stopping: {config_path}."
        )

    batch_size = int(data_config.get("batch_size", -1))
    if batch_size != 64:
        raise ValueError(
            f"Experiment A requires batch_size=64, got {batch_size} "
            f"in {config_path}."
        )

    if bool(data_config.get("spatial_split", False)):
        raise ValueError(
            "Experiment A must use the same basins with temporal splitting; "
            f"spatial_split=True was found in {config_path}."
        )

    stage = classify_config(config_path)
    dependency = extract_checkpoint_dependency(config)
    name = config_path.stem.lower()

    expected_joint_epochs = manifest.get("joint_epochs")
    expected_pretrain_epochs = manifest.get(
        "pretrain_epochs"
    )
    actual_epochs = int(training_config.get("epochs", -1))

    if stage == "pretrain":
        expected_epochs = expected_pretrain_epochs
    else:
        expected_epochs = expected_joint_epochs

    if (
        expected_epochs is not None
        and actual_epochs != int(expected_epochs)
    ):
        raise ValueError(
            f"Unexpected epochs={actual_epochs} in {config_path}; "
            f"manifest requires {int(expected_epochs)}."
        )

    if "_stl_q_" in name:
        if architecture != "stl":
            raise ValueError(
                f"STL-Q must use architecture=stl: {config_path}."
            )
        if target_weights != {"streamflow": 1.0}:
            raise ValueError(
                f"Invalid STL-Q targets/weights in {config_path}: "
                f"{target_weights}."
            )
        if sample_filter != expected_training_filter(
            "streamflow"
        ):
            raise ValueError(
                f"Invalid STL-Q sample_filter in {config_path}: "
                f"{sample_filter}."
            )

    elif "_stl_ssm_" in name:
        if architecture != "stl":
            raise ValueError(
                f"STL-SSM must use architecture=stl: {config_path}."
            )
        if target_weights != {"ssm": 1.0}:
            raise ValueError(
                f"Invalid STL-SSM targets/weights in {config_path}: "
                f"{target_weights}."
            )
        if sample_filter != expected_training_filter("ssm"):
            raise ValueError(
                f"Invalid STL-SSM sample_filter in {config_path}: "
                f"{sample_filter}."
            )

    elif stage == "pretrain":
        if architecture not in {"hps", "cgc"}:
            raise ValueError(
                f"Q pretraining requires HPS or CGC: {config_path}."
            )
        if target_weights != {
            "streamflow": 1.0,
            "ssm": 0.0,
        }:
            raise ValueError(
                f"Invalid Q-pretrain targets/weights in {config_path}: "
                f"{target_weights}."
            )
        if sample_filter != expected_training_filter(
            "streamflow"
        ):
            raise ValueError(
                f"Invalid Q-pretrain sample_filter in {config_path}: "
                f"{sample_filter}."
            )

    else:
        if architecture not in {"hps", "cgc"}:
            raise ValueError(
                f"Joint Q-SSM runs require HPS or CGC: {config_path}."
            )
        if set(target_weights) != {"streamflow", "ssm"}:
            raise ValueError(
                f"Joint Q-SSM targets are invalid in {config_path}: "
                f"{target_weights}."
            )
        if any(weight <= 0.0 for weight in target_weights.values()):
            raise ValueError(
                f"Joint Q-SSM weights must be positive in {config_path}: "
                f"{target_weights}."
            )
        if sample_filter is not None:
            raise ValueError(
                "Joint Q-SSM runs must retain all dates and use "
                f"per-task masks, but found {sample_filter} in "
                f"{config_path}."
            )

    if stage == "finetune" and dependency is None:
        raise ValueError(
            f"Fine-tuning config is missing a checkpoint dependency: "
            f"{config_path}"
        )

    if stage != "finetune" and dependency is not None:
        raise ValueError(
            "Only fine-tuning configs may declare an initialization "
            f"dependency: {config_path}"
        )


def load_torch_checkpoint(
    checkpoint_path: Path,
) -> Dict[str, Any]:
    """Load a trusted local checkpoint on CPU."""
    try:
        checkpoint = torch.load(
            checkpoint_path,
            map_location="cpu",
            weights_only=False,
        )
    except TypeError:
        checkpoint = torch.load(
            checkpoint_path,
            map_location="cpu",
        )

    if not isinstance(checkpoint, dict):
        raise ValueError(
            f"Checkpoint is not a dictionary: {checkpoint_path}"
        )

    return checkpoint


def get_experiment_name(
    config_path: Path,
    config: ConfigDict,
) -> str:
    """Return the validated experiment name used below experiments/."""
    experiment = config.get("experiment", {})
    if not isinstance(experiment, dict):
        raise ValueError(
            f"Missing experiment block in {config_path}."
        )

    name = str(experiment.get("name", "")).strip()
    if not name:
        raise ValueError(
            f"Missing experiment.name in {config_path}."
        )

    return name


def get_target_epochs(
    config_path: Path,
    config: ConfigDict,
) -> int:
    """Return the positive target epoch count for one run."""
    training = config.get("training", {})
    if not isinstance(training, dict):
        raise ValueError(
            f"Missing training block in {config_path}."
        )

    epochs = int(training.get("epochs", 0))
    if epochs <= 0:
        raise ValueError(
            f"Invalid training.epochs={epochs} in {config_path}."
        )

    return epochs


def read_checkpoint_epoch(
    checkpoint_path: Path,
) -> Optional[int]:
    """Return a checkpoint epoch, or None when the file is absent."""
    if not checkpoint_path.exists():
        return None

    checkpoint = load_torch_checkpoint(checkpoint_path)
    epoch = checkpoint.get("epoch")

    if epoch is None:
        raise ValueError(
            f"Checkpoint has no epoch field: {checkpoint_path}"
        )

    return int(epoch)


def is_training_complete(
    experiment_dir: Path,
    target_epochs: int,
) -> bool:
    """Return True only when final_model.pth reaches the target epoch."""
    final_path = experiment_dir / "final_model.pth"
    final_epoch = read_checkpoint_epoch(final_path)

    if final_epoch is None:
        return False

    if final_epoch > target_epochs:
        raise ValueError(
            "Final checkpoint exceeds the configured target epoch: "
            f"{final_path} has epoch={final_epoch}, "
            f"target={target_epochs}."
        )

    return final_epoch == target_epochs


def find_resume_checkpoint(
    experiment_dir: Path,
    target_epochs: int,
) -> Optional[Path]:
    """Return the canonical partial-training checkpoint when available."""
    candidate = experiment_dir / "last_model.pth"
    epoch = read_checkpoint_epoch(candidate)

    if epoch is None:
        return None

    if epoch <= 0 or epoch > target_epochs:
        raise ValueError(
            f"Invalid resume epoch={epoch} in {candidate}; "
            f"target={target_epochs}."
        )

    return candidate.resolve()


def is_test_complete(
    experiment_dir: Path,
) -> bool:
    """Return True when both required test exports already exist."""
    return (
        (experiment_dir / "test_per_basin_metrics.csv").exists()
        and (
            experiment_dir
            / "test_predictions_and_weights.nc"
        ).exists()
    )


def write_run_manifest(
    *,
    run_manifest_path: Path,
    source_manifest: Path,
    args: argparse.Namespace,
    records: List[ConfigDict],
) -> None:
    """Persist the runner state after every completed decision."""
    write_json(
        {
            "source_manifest": str(source_manifest),
            "mode": args.mode,
            "subset": args.subset,
            "device": args.device,
            "dry_run": bool(args.dry_run),
            "skip_completed": bool(args.skip_completed),
            "resume_partial": bool(args.resume_partial),
            "executed": records,
        },
        run_manifest_path,
    )


def build_command(
    *,
    python_executable: str,
    config_path: Path,
    mode: str,
    device: str,
    extra_args: Sequence[str],
    init_checkpoint: Optional[Path],
    resume_checkpoint: Optional[Path],
    strict_init: bool,
) -> List[str]:
    """Build one main.py command."""
    command = [
        python_executable,
        "main.py",
        "--config",
        str(config_path),
        "--mode",
        mode,
        "--device",
        device,
    ]

    if mode == "train" and resume_checkpoint is not None:
        command.extend(
            [
                "--resume_checkpoint",
                str(resume_checkpoint),
            ]
        )
    elif mode == "train" and init_checkpoint is not None:
        command.extend(
            [
                "--init_checkpoint",
                str(init_checkpoint),
            ]
        )

        if strict_init:
            command.append("--strict_init")

    command.extend(extra_args)
    return command


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Run Chapter 4 Experiment A Q-to-SSM configurations."
        )
    )

    parser.add_argument(
        "--manifest",
        default=Path(
            "mtl_cgc/configs/ch4_qssm/"
            "ch4a_q_to_ssm_manifest.json"
        ),
        type=Path,
    )
    parser.add_argument(
        "--project-root",
        default=Path("."),
        type=Path,
    )
    parser.add_argument(
        "--experiments-root",
        default=Path("experiments"),
        type=Path,
    )
    parser.add_argument(
        "--python",
        default=sys.executable,
    )
    parser.add_argument(
        "--mode",
        choices=["train", "test"],
        default="train",
    )
    parser.add_argument(
        "--subset",
        choices=[
            "all",
            "baselines",
            "pretrain",
            "finetune",
            "evaluation",
        ],
        default="all",
    )
    parser.add_argument(
        "--device",
        default="auto",
    )
    parser.add_argument(
        "--strict-init",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Require exact model-key matching when loading a "
            "Q-pretraining checkpoint."
        ),
    )
    parser.add_argument(
        "--skip-completed",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Skip train runs whose final_model.pth already reaches "
            "the configured target epoch, and skip completed test exports."
        ),
    )
    parser.add_argument(
        "--resume-partial",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Resume incomplete train runs from last_model.pth when available."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
    )
    parser.add_argument(
        "--extra-arg",
        action="append",
        default=[],
        help=(
            "Append one argument to every main.py command. "
            "This option may be repeated."
        ),
    )

    return parser.parse_args()


def main() -> None:
    """Execute the selected Experiment A configurations."""
    args = parse_args()

    project_root = args.project_root.resolve()
    manifest_path = resolve_project_path(
        args.manifest,
        project_root,
    )
    experiments_root = resolve_project_path(
        args.experiments_root,
        project_root,
    )

    manifest, manifest_config_paths = load_manifest(
        manifest_path
    )
    config_paths = [
        resolve_project_path(path, project_root)
        for path in manifest_config_paths
    ]
    config_paths = order_configs(config_paths)
    config_paths = select_configs(
        config_paths,
        args.subset,
    )

    run_manifest_path = (
        experiments_root
        / "ch4_qssm"
        / (
            f"{manifest_path.stem}_run_"
            f"{args.mode}_{args.subset}.json"
        )
    )

    records: List[ConfigDict] = []

    for config_path in config_paths:
        if not config_path.exists():
            raise FileNotFoundError(
                f"Configuration not found: {config_path}"
            )

        config = load_yaml(config_path)
        audit_experiment_a_config(
            config_path,
            config,
            manifest,
        )

        stage = classify_config(config_path)
        dependency = extract_checkpoint_dependency(config)
        experiment_name = get_experiment_name(
            config_path,
            config,
        )
        target_epochs = get_target_epochs(
            config_path,
            config,
        )
        experiment_dir = experiments_root / experiment_name

        record: ConfigDict = {
            "config": str(config_path),
            "experiment_name": experiment_name,
            "experiment_dir": str(experiment_dir),
            "stage": stage,
            "mode": args.mode,
            "target_epochs": target_epochs,
            "dependency": dependency,
            "init_checkpoint": None,
            "resume_checkpoint": None,
            "command": [],
            "status": "pending",
        }
        records.append(record)

        if (
            args.mode == "train"
            and args.skip_completed
            and is_training_complete(
                experiment_dir,
                target_epochs,
            )
        ):
            record["status"] = "skipped_completed"
            print(
                f"Skipped completed training: {experiment_name} "
                f"(epoch={target_epochs})."
            )
            write_run_manifest(
                run_manifest_path=run_manifest_path,
                source_manifest=manifest_path,
                args=args,
                records=records,
            )
            continue

        if (
            args.mode == "test"
            and args.skip_completed
            and is_test_complete(experiment_dir)
        ):
            record["status"] = "skipped_test_completed"
            print(
                f"Skipped completed test exports: {experiment_name}."
            )
            write_run_manifest(
                run_manifest_path=run_manifest_path,
                source_manifest=manifest_path,
                args=args,
                records=records,
            )
            continue

        init_checkpoint: Optional[Path] = None
        resume_checkpoint: Optional[Path] = None

        if args.mode == "train" and args.resume_partial:
            resume_checkpoint = find_resume_checkpoint(
                experiment_dir,
                target_epochs,
            )

            if resume_checkpoint is not None:
                resume_epoch = read_checkpoint_epoch(
                    resume_checkpoint
                )
                print(
                    "Resolved resume checkpoint: "
                    f"{config_path.name} <- {resume_checkpoint} "
                    f"(epoch={resume_epoch}/{target_epochs})"
                )

        # A fine-tuning run uses its own partial checkpoint when resuming.
        # The upstream Q-pretraining checkpoint is only used for a new run.
        if (
            args.mode == "train"
            and resume_checkpoint is None
            and dependency is not None
        ):
            if args.dry_run:
                init_checkpoint = (
                    experiments_root
                    / dependency
                    / CHECKPOINT_PRIORITY[0]
                ).resolve()

                print(
                    "Dry-run initialization dependency: "
                    f"{config_path.name} <- {init_checkpoint}"
                )
            else:
                init_checkpoint = resolve_dependency_checkpoint(
                    dependency,
                    experiments_root,
                )

                print(
                    "Resolved initialization checkpoint: "
                    f"{config_path.name} <- {init_checkpoint}"
                )

        command = build_command(
            python_executable=args.python,
            config_path=config_path,
            mode=args.mode,
            device=args.device,
            extra_args=args.extra_arg,
            init_checkpoint=init_checkpoint,
            resume_checkpoint=resume_checkpoint,
            strict_init=bool(args.strict_init),
        )

        record["init_checkpoint"] = (
            str(init_checkpoint)
            if init_checkpoint is not None
            else None
        )
        record["resume_checkpoint"] = (
            str(resume_checkpoint)
            if resume_checkpoint is not None
            else None
        )
        record["command"] = command
        record["status"] = "running"

        print("\n" + "=" * 100)
        print(f"Stage   : {stage}")
        print(f"Config  : {config_path.name}")
        print("Command :", " ".join(command))
        print("=" * 100)

        try:
            return_code = run_command(
                command,
                cwd=project_root,
                dry_run=args.dry_run,
            )

            if isinstance(return_code, int) and return_code != 0:
                raise RuntimeError(
                    f"Command returned non-zero code {return_code}: "
                    f"{config_path}"
                )
        except Exception as error:
            record["status"] = "failed"
            record["error"] = repr(error)

            write_run_manifest(
                run_manifest_path=run_manifest_path,
                source_manifest=manifest_path,
                args=args,
                records=records,
            )
            raise

        record["status"] = (
            "dry_run"
            if args.dry_run
            else "completed"
        )

        write_run_manifest(
            run_manifest_path=run_manifest_path,
            source_manifest=manifest_path,
            args=args,
            records=records,
        )

    print(f"\nExperiment A run manifest: {run_manifest_path}")


if __name__ == "__main__":
    main()
